2019-06-09 15:14:19,407 INFO ManagerLogbook.Web.Program - Application - Main is invoked
2019-06-09 15:16:46,836 INFO ManagerLogbook.Web.Controllers.HomeController - Unexpected exception occured:
2019-06-10 11:06:53,455 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:07:02,298 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:07:09,744 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:07:24,644 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:09:50,982 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:10:49,427 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:12:24,158 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:14:08,761 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:15:24,372 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 11:15:32,114 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.NotesController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Web.Areas.Manager.Controllers.NotesController.Index() in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\NotesController.cs:line 70
2019-06-10 22:59:37,200 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-10 23:00:00,211 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-10 23:00:35,109 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-10 23:02:39,262 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-10 23:03:07,640 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-10 23:06:23,511 ERROR ManagerLogbook.Web.Areas.Manager.Controllers.UsersController - Unexpected exception occured:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ManagerLogbook.Services.Mappers.NoteDTOMapper.ToDTO(Note entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\NoteDTOMapper.cs:line 15
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.<>c.<ToDTO>b__0_0(Note x) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 22
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ManagerLogbook.Services.Mappers.LogbookDTOMapper.ToDTO(Logbook entity) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\Mappers\LogbookDTOMapper.cs:line 16
   at ManagerLogbook.Services.LogbookService.GetLogbookById(Int32 logbookId) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 73
   at ManagerLogbook.Web.Areas.Manager.Controllers.UsersController.SwitchLogbook(ManagerViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Manager\Controllers\UsersController.cs:line 41
2019-06-12 00:08:51,482 ERROR ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController - Unexpected exception occured:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Logbooks_BusinessUnits_BusinessUnitId". The conflict occurred in database "ManagerLogbook", table "dbo.BusinessUnits", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ManagerLogbook.Services.LogbookService.CreateLogbookAsync(String name, Int32 businessUnitId, String picture) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 51
   at ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController.Create(LogbookViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Admin\Controllers\LogbooksController.cs:line 64
2019-06-12 00:09:31,151 ERROR ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController - Unexpected exception occured:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Logbooks_BusinessUnits_BusinessUnitId". The conflict occurred in database "ManagerLogbook", table "dbo.BusinessUnits", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ManagerLogbook.Services.LogbookService.CreateLogbookAsync(String name, Int32 businessUnitId, String picture) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 51
   at ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController.Create(LogbookViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Admin\Controllers\LogbooksController.cs:line 64
2019-06-12 00:11:25,178 ERROR ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController - Unexpected exception occured:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Logbooks_BusinessUnits_BusinessUnitId". The conflict occurred in database "ManagerLogbook", table "dbo.BusinessUnits", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ManagerLogbook.Services.LogbookService.CreateLogbookAsync(String name, Int32 businessUnitId, String picture) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\LogBookService.cs:line 51
   at ManagerLogbook.Web.Areas.Admin.Controllers.LogbooksController.Create(LogbookViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Admin\Controllers\LogbooksController.cs:line 64
2019-06-12 09:20:28,226 ERROR ManagerLogbook.Web.Areas.Admin.Controllers.BusinessUnitsController - Unexpected exception occured:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_BusinessUnits_BusinessUnitCategories_BusinessUnitCategoryId". The conflict occurred in database "ManagerLogbook", table "dbo.BusinessUnitCategories", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ManagerLogbook.Services.BusinessUnitService.CreateBusinnesUnitAsync(String brandName, String address, String phoneNumber, String email, String information, Int32 businessUnitCategoryId, Int32 townId, String picture) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\BusinessUnitService.cs:line 48
   at ManagerLogbook.Web.Areas.Admin.Controllers.BusinessUnitsController.Create(BusinessUnitViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Admin\Controllers\BusinessUnitsController.cs:line 66
2019-06-12 09:25:17,430 ERROR ManagerLogbook.Web.Areas.Admin.Controllers.BusinessUnitsController - Unexpected exception occured:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_BusinessUnits_BusinessUnitCategories_BusinessUnitCategoryId". The conflict occurred in database "ManagerLogbook", table "dbo.BusinessUnitCategories", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at ManagerLogbook.Services.BusinessUnitService.CreateBusinnesUnitAsync(String brandName, String address, String phoneNumber, String email, String information, Int32 businessUnitCategoryId, Int32 townId, String picture) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Services\BusinessUnitService.cs:line 48
   at ManagerLogbook.Web.Areas.Admin.Controllers.BusinessUnitsController.Create(BusinessUnitViewModel model) in E:\TelerikAlpha\AlphaProgram2019\Repositories\Fourth_Final_Project_3_Repo\ManagerLogbook\ManagerLogbook\ManagerLogbook.Web\Areas\Admin\Controllers\BusinessUnitsController.cs:line 66
